language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install --dev